### ISSUE TITLE
cannot synchronize hnswlib on conda-forge channel

### ISSUE THREAD

**Issue by yihming** [conda-forge/hnswlib-feedstock#19]
### Conda-forge documentation

- [X] I could not solve my problem using the conda-forge documentation.

### Installed packages

```shell
hnswlib
```

### Environment info

```shell
hnswlib-feedstock in conda-forge organization
```

### Issue

I'm a maintainer of [hnswlib-feedstock](https://github.com/conda-forge/hnswlib-feedstock) on `conda-forge` channel.

However, after updating [meta.yml](https://github.com/conda-forge/hnswlib-feedstock/blob/main/recipe/meta.yaml) in the repo to `hnswlib` version 0.6.2, its version on the channel (https://anaconda.org/conda-forge/hnswlib) is still 0.5.1, which was over 1 year ago.

Is this feedstock repo in the blacklist of `conda-forge`? I don't know where I should approach regarding this issue. So could you please give me a hand?

Many thanks!

Sincerely,
Yiming

**Comment by jakirkham** [comment]
Transferred to the feedstock in question

The issue is this line is effectively disabling CI. My guess is there is a typo here

https://github.com/conda-forge/hnswlib-feedstock/blob/cd333d29895ae747252320ff7b3ddfd6020f193a/recipe/meta.yaml#L14

**Comment by yihming** [comment]
@jakirkham Thank you so much for pointing out this typo! I've fixed it in a new PR, and will see if it could resolve the synchronization issue.

**Comment by yihming** [comment]
@jakirkham Now it's synchronized. The issue is resolved. Thank you again for your help!

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/hnswlib-feedstock/pull/20
